-- use this file to map the AP item ids to your items
-- first value is the code of the target item and the second is the item type (currently only "toggle", "progressive" and "consumable" but feel free to expand for your needs!)
-- here are the SM items as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/item_mapping.lua
local base_id = 0

ITEM_MAPPING = {
    [1] = { "FBubble", "toggle" },
    [2] = { "BBell", "toggle" },
    [3] = { "GLug", "toggle" },
    [4] = { "SStone", "consumable" },
    [5] = { "DMilk", "toggle" },
    [6] = { "BMilk", "toggle" },
    [7] = { "CAKey", "toggle" },
    [8] = { "MPass", "toggle" },
    [9] = { "BClothes", "toggle" },
    [10] = { "HDaikon", "toggle" },
    [11] = { "HDango", "toggle" },
    [12] = { "SFrag", "consumable" },
    [13] = { "LHalo", "toggle" },
    [14] = { "DLetter", "toggle" },
    [15] = { "ALetter", "toggle" },
    [16] = { "SSlime", "toggle" },
    [17] = { "RWine", "toggle" },
    [18] = { "BJelly", "toggle" },
    [19] = { "MContract", "toggle" },
    [20] = { "FDeed", "toggle" },
    [21] = { "MimicKey", "toggle" },
    [22] = { "FKey", "toggle" },
    [23] = { "GAKey", "toggle" },
    [98] = { "GHead", "toggle" },
    [99] = { "GCard", "toggle" },
    [100] = { "VIPKey", "toggle" },
    -- [24] = { "Goblin Bomb", "toggle" },
     --[25] = { "Frilly Panties", "toggle" },
    -- [26] = { "Disarming Bell", "toggle" },
    [27] = { "GForm", "toggle" },
    [28] = { "SForm", "toggle" },
    -- [29] = { "Harpy Feather", "toggle" },
    -- [30] = { "Magical Mushroom", "toggle" },
    --[31] = { "Slime Sentry", "toggle" },
    -- [32] = { "Ring Of The Moon", "toggle" },
    -- [33] = { "Ring Of The Sun", "toggle" },
    -- [34] = { "Haunted Scythe", "toggle" },
    --[35] = { "Demonic Cuff", "toggle" },
    [37] = { "FCat", "toggle" },
    -- [38] = { "Heart Necklace", "toggle" },
   -- [39] = { "Star Bracelet", "toggle" },
   -- [40] = { "Magnetic Hairpin", "toggle" },
   -- [41] = { "Yellow Frog Talisman", "toggle" },
   -- [42] = { "Blue Frog Talisman", "toggle" },
   -- [43] = { "Sacrificial Dagger", "toggle" },
   -- [44] = { "Mind Mushroom", "toggle" },
   -- [45] = { "Flutterknife Garter", "toggle" },
   -- [46] = { "Cursed Talisman", "toggle" },
    [47] = { "HP", "consumable" }, 
    [48] = { "MP", "consumable" }, 
    --[49] = { "Wand Upgrade", "toggle" },
    [50] = { "Peach", "consumable" },
    [51] = { "BBubbleMale", "toggle" },
    [52] = { "GCrystal", "toggle" },
    [53] = { "PPCrystal", "toggle" },
    [54] = { "DWings", "toggle" },
    [55] = { "AFeather", "toggle" },
    [56] = { "MScale", "toggle" },
    --[57] = { "Lucky Coin", "toggle" },
    --[58] = { "Loose Change", "toggle" },
    [59] = { "WCB", "toggle" },
    [60] = { "GCB", "toggle" },
    [61] = { "BlackCos", "toggle" },
    [63] = { "RedCos", "toggle" },
    [64] = { "NunCos", "toggle" },
    [65] = { "PriestCos", "toggle" },
    [66] = { "MikoCos", "toggle" },
    [67] = { "FarmCos", "toggle" },
    [68] = { "CatCos", "toggle" },
    [69] = { "GobCos", "toggle" },
    [70] = { "MaidCos", "toggle" },
    [71] = { "PigCos", "toggle" },
    [72] = { "BunCos", "toggle" },
    [73] = { "RatCos", "toggle" },
    [74] = { "NurseCos", "toggle" },
    [75] = { "FishCos", "toggle" },
    [76] = { "DomCos", "toggle" },
    [77] = { "MailCos", "toggle" },
    [78] = { "FairyCos", "toggle" },
    [79] = { "AlchCos", "toggle" },
    [80] = { "RHKey", "toggle" },
    [81] = { "GCKey", "toggle" },
    [82] = { "TBKey", "toggle" },
    [83] = { "SCDKey", "toggle" },
    [84] = { "SCKey", "toggle" },
    [85] = { "FBKey", "toggle" },
    [86] = { "GQKey", "toggle" },
    [87] = { "RGKey", "toggle" },
    [88] = { "CTKey", "toggle" },
    [89] = { "DBKey", "toggle" },
    [90] = { "SSBKey", "toggle" },
    [91] = { "CSKey", "toggle" },
    [92] = { "AAKey", "toggle" },
    [93] = { "SGKey", "toggle" },
    [94] = { "CDKey", "toggle" },
    [95] = { "SBKey", "toggle" },
    [96] = { "FFDKey", "toggle" },
    [97] = { "ChaosK", "consumable" },
    --[101] = { "HP Heal", "toggle" },
    --[102] = { "MP Heal", "toggle" },
    --[103] = { "Peach Recharge", "toggle" },
    --[104] = { "Sex Thoughts", "toggle" },
    --[105] = { "Armor Barrier", "toggle" },
    [106] = { "Peachy Peach Upgrade", "toggle" },
    [107] = { "AGacha", "progressive" },
    [108] = { "BGacha", "progressive" },
    [109] = { "ADGacha", "progressive" },
    [110] = { "MGacha", "progressive" },
    [111] = { "PGacha", "toggle" },

    --Warps
    [201] = {"Sensei Warp", "toggle"},
    [202] = {"Witchy Warp", "toggle"},
    [203] = {"Goblin Warp", "toggle"},
    [204] = {"Spirit Warp", "toggle"},
    [205] = {"Shady Warp", "toggle"},
    [206] = {"Ghost Entrace Warp", "toggle"},
    [207] = {"Ghost Castle Warp", "toggle"},
    [208] = {"Jigoku Warp", "toggle"},
    [209] = {"Club Demon Warp", "toggle"},
    [210] = {"Tengoku Warp", "toggle"},
    [211] = {"Angelic Hallway Warp", "toggle"},
    [212] = {"Fungal Forest Warp", "toggle"},
    [213] = {"Slime_Citadel Warp", "toggle"},
    [214] = {"Slimy_Depths Warp", "toggle"},
    [215] = {"Umi Umi Warp", "toggle"},
    [216] = {"Chaos Castle Warp", "toggle"},
}
    

--[[     #Gacha 
    #"SP Figure 1":151,
    #"AG Figure 1":152,
    #"AG Figure 2":153,
    #"AG Figure 3":154,
    #"AG Figure 4":155,
    #"AG Figure 5":156,
    #"AG Figure 6":157,
    #"AG Figure 7":158,
    #"AG Figure 8":159,
    #"AG Figure 9":160,
    #"AG Figure 10":161,
    #"BG Figure 1":162,
    #"BG Figure 2":163,
    #"BG Figure 3":164,
    #"BG Figure 4":165,
    #"BG Figure 5":166,
    #"BG Figure 6":167,
    #"BG Figure 7":168,
    #"BG Figure 8":169,
    #"BG Figure 9":170,
    #"BG Figure 10":171,
    #"AD Figure 1":172,
    #"AD Figure 2":173,
    #"AD Figure 3":174,
    #"AD Figure 4":175,
    #"AD Figure 5":176,
    #"AD Figure 6":177,
    #"AD Figure 7":178,
    #"AD Figure 8":179,
    #"AD Figure 9":180,
    #"AD Figure 10":181,
    #"MG Figure 1":182,
    #"MG Figure 2":183,
    #"MG Figure 3":184,
    #"MG Figure 4":185,
    #"MG Figure 5":186,
    #"MG Figure 6":187,
    #"MG Figure 7":188,
    #"MG Figure 8":189,
    #"MG Figure 9":190,
    #"MG Figure 10":191,
#} ]]
