-- use this file to map the AP item ids to your items
-- first value is the code of the target item and the second is the item type (currently only "toggle", "progressive" and "consumable" but feel free to expand for your needs!)
-- here are the SM items as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/item_mapping.lua
local base_id = 0

ITEM_MAPPING = {
    -- [1] = { "Goblin Bomb", "toggle" },
    [2] = { "GForm", "toggle" },
    [3] = { "SForm", "toggle" },
    --[4] = { "Harpy Feather", "toggle" },
    --[5] = { "Magnetic Hairpin", "toggle" },
    --[6] = { "Sacrificial Dagger", "toggle" },
    --[7] = { "Flutterknife Garter", "toggle" },
    [8] = { "HP", "consumable" }, 
    [9] = { "MP", "consumable" }, 
    --[10] = { "Wand Upgrade", "toggle" },
    [11] = { "Peach", "consumable" },
    [12] = { "BBubble", "toggle" },
    [13] = { "GCrystal", "toggle" },
    [14] = { "DWings", "toggle" },
    [15] = { "AFeather", "toggle" },
    [16] = { "MScale", "toggle" },
    --[17] = { "Lucky Coin", "toggle" },
    --[18] = { "Loose Change", "toggle" },
    [19] = { "WCB", "toggle" },
    [20] = { "CCB", "toggle" },
    [21] = { "BlackCos", "toggle" },
    [22] = { "RedCos", "toggle" },
    [24] = { "RatCos", "toggle" },
    [25] = { "FishCos", "toggle" },
    [26] = { "FairyCos", "toggle" },
    [27] = { "RHKey", "toggle" },
    [28] = { "GCKey", "toggle" },
    [29] = { "TBKey", "toggle" },
    [30] = { "SCDKey", "toggle" },
    [31] = { "SCKey", "toggle" },
    [32] = { "FBKey", "toggle" },
    [33] = { "GQKey", "toggle" },
    [34] = { "RGKey", "toggle" },
    [35] = { "CTKey", "toggle" },
    [36] = { "DBKey", "toggle" },
    [37] = { "SSBKey", "toggle" },
    [38] = { "CSKey", "toggle" },
    [40] = { "SGKey", "toggle" },
    [41] = { "CDKey", "toggle" },
    [42] = { "SBKey", "toggle" },
    [43] = { "FFDKey", "toggle" },
    [45] = { "ChaosK", "consumable" },
    --[46] = { "HP Heal", "toggle" },
    --[47] = { "MP Heal", "toggle" },
    --[48] = { "Peach Recharge", "toggle" },
    [49] = { "Armor Barrier", "consumable" },
    [50] = { "Peachy Peach Upgrade", "toggle" },

    --Gacha
    [142] = { "AGacha", "consumable" },
    [143] = { "BGacha", "consumable" },
    [144] = { "ADGacha", "consumable" },
    [145] = { "MGacha", "consumable" },
    [146] = { "PGacha", "toggle" },

    --Shop Items
    [151] = { "FBubble", "toggle" },
    [168] = { "CatCos", "toggle" },
    [169] = { "GobCos", "toggle" },
    [170] = { "NunCos", "toggle" },
    [171] = { "PriestCos", "toggle" },
    [172] = { "MikoCos", "toggle" },
    [173] = { "FarmCos", "toggle" },
    [174] = { "NurseCos", "toggle" },
    [175] = { "MailCos", "toggle" },
    [176] = { "MaidCos", "toggle" },
    [177] = { "PigCos", "toggle" },
    [178] = { "DomCos", "toggle" },
    [179] = { "AlchCos", "toggle" },



    --Quest Items
    [201] = { "GHead", "toggle" },
    [202] = { "GCard", "toggle" },
    [203] = { "VIPKey", "toggle" },
    [204] = { "BBell", "toggle" },
    [205] = { "GLug", "toggle" },
    [206] = { "SStone", "consumable" },
    [207] = { "DMilk", "toggle" },
    [208] = { "BMilk", "toggle" },
    [209] = { "CAKey", "toggle" },
    [210] = { "MPass", "toggle" },
    [211] = { "BClothes", "toggle" },
    [212] = { "HDaikon", "toggle" },
    [213] = { "HDango", "toggle" },
    [214] = { "SFrag", "consumable" },
    [215] = { "LHalo", "toggle" },
    [216] = { "DLetter", "toggle" },
    [217] = { "ALetter", "toggle" },
    [218] = { "SSlime", "toggle" },
    [219] = { "RWine", "toggle" },
    [220] = { "BJelly", "toggle" },
    [221] = { "MContract", "toggle" },
    [222] = { "FDeed", "toggle" },
    [223] = { "MimicKey", "toggle" },
    [224] = { "FKey", "toggle" },
    [225] = { "GAKey", "toggle" },
    [226] = { "Reward", "consumable" },
    [227] = { "BunCos", "toggle" },
    [228] = { "AAKey", "toggle" },

    --Warps
    [251] = {"Sensei Warp", "toggle"},
    [252] = {"Witchy Warp", "toggle"},
    [253] = {"Goblin Warp", "toggle"},
    [254] = {"Spirit Warp", "toggle"},
    [255] = {"Shady Warp", "toggle"},
    [256] = {"Ghost Entrace Warp", "toggle"},
    [257] = {"Ghost Castle Warp", "toggle"},
    [258] = {"Jigoku Warp", "toggle"},
    [259] = {"Club Demon Warp", "toggle"},
    [260] = {"Tengoku Warp", "toggle"},
    [261] = {"Angelic Hallway Warp", "toggle"},
    [262] = {"Fungal Forest Warp", "toggle"},
    [263] = {"Slime_Citadel Warp", "toggle"},
    [264] = {"Slimy_Depths Warp", "toggle"},
    [265] = {"Umi Umi Warp", "toggle"},
    [266] = {"Chaos Castle Warp", "toggle"},
}


--[[    
    Gacha Capsules 
    [101] = {"Figure 1"},
    [102] = {"Figure 1"},
    [103] = {"Figure 2"},
    [104] = {"Figure 3"},
    [105] = {"Figure 4"},
    [106] = {"Figure 5"},
    [107] = {"Figure 6"},
    [108] = {"Figure 7"},
    [109] = {"Figure 8"},
    [110] = {"Figure 9"},
    [111] = {"Figure 10"},
    [112] = {"Figure 1"},
    [113] = {"Figure 2"},
    [114] = {"Figure 3"},
    [115] = {"Figure 4"},
    [116] = {"Figure 5"},
    [117] = {"Figure 6"},
    [118] = {"Figure 7"},
    [119] = {"Figure 8"},
    [120] = {"Figure 9"},
    [121] = {"Figure 10"},
    [122] = {"Figure 1"},
    [123] = {"Figure 2"},
    [124] = {"Figure 3"},
    [125] = {"Figure 4"},
    [126] = {"Figure 5"},
    [127] = {"Figure 6"},
    [128] = {"Figure 7"},
    [129] = {"Figure 8"},
    [130] = {"Figure 9"},
    [131] = {"Figure 10"},
    [132] = {"Figure 1"},
    [133] = {"Figure 2"},
    [134] = {"Figure 3"},
    [135] = {"Figure 4"},
    [136] = {"Figure 5"},
    [137] = {"Figure 6"},
    [138] = {"Figure 7"},
    [139] = {"Figure 8"},
    [140] = {"Figure 9"},
    [141] = {"Figure 10"},

    Unimportant Shop Items
    --[152] = { "Frilly Panties", "toggle" },
    --[153] = { "Disarming Bell", "toggle" },
    --[154] = { "Demonic Cuff", "toggle" },
    --[155] = { "Ring Of The Moon", "toggle" },
    --[156] = { "Magical Mushroom", "toggle" },
    --[157] = { "Ring Of The Sun", "toggle" },
    --[158] = { "Slime Sentry", "toggle" },
    --[159] = { "Haunted Scythe", "toggle" },
    --[160] = { "FCat", "toggle" },
    --[167] = { "PPCrystal", "toggle" },
    --[161] = { "Heart Necklace", "toggle" },
    --[162] = { "Star Bracelet", "toggle" },
    --[163] = { "Cursed Talisman", "toggle" },
    --[164] = { "Yellow Frog Talisman", "toggle" },
    --[165] = { "Blue Frog Talisman", "toggle" },
    --[166] = { "Mind Mushroom", "toggle" },

    Junk and Traps
    [301] = {"Nothing", "toggle"},
    [302] = {"Sex Thoughts", "toggle"},
#} ]]
