-- use this file to map the AP location ids to your locations
-- to reference a location in Pop use @ in the beginning and then path to the section (more info: https://github.com/black-sliver/PopTracker/blob/master/doc/PACKS.md#locations)
-- to reference an item use it's code
-- here are the SM locations as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/location_mapping.lua
local base_id = 0

LOCATION_MAPPING = {
    [1] = { "@Witchy Woods/Sensei's Hut/Chest" }, --"Sensei's Hut, Navy Witch Costume Chest"
    [2] = { "@Witchy Woods/Sensei's Hut/Chest Behind Laser" },
    [3] = { "@Witchy Woods/Past the Hut/Peachy Peaches" },
    [4] = { "@Witchy Woods/Rundown House Save/Hidden Chest" },
    [5] = { "@Witchy Woods/Mimic Chest Key Room/Chest" },
    [6] = { "@Witchy Woods/Secret Cave/Chest" },
    [7] = { "@Witchy Woods/Mimi/Hidden Chest" },
    [8] = { "@Witchy Woods/Rundown House/Chest Behind Door" },
    [9] = { "@Goblin Caves/Past Man Cave/Chest" },
    [10] = { "@Goblin Caves/Gerry G. Atric/Chest" },
    [11] = { "@Goblin Caves/Hidden Alcove/Chest" },
    [12] = { "@Goblin Caves/Beside Flip Magic Platform/Chest" },
    [13] = { "@Goblin Caves/After Chaos Fight/Chest" },
    [14] = { "@Goblin Caves/Boss Key Room/Chest" },
    [15] = { "@Goblin Caves/Boss Key Room/Big Chest" },
    [16] = { "@Goblin Caves/Goblin Queen/Chaos Key Piece" },
    [17] = { "@Goblin Caves/Flying Fairy/Chest" },
    [18] = { "@Witchy Woods/Great Fairy/Fairy Reward" },

--Spirit City

    [31] = { "@Spirit City/Rare Items Shop/Roof Chest" },
    [32] = { "@Spirit City/Ancient Being/Chest" },
    [33] = { "@Spirit City/Ghostly Castle Key/Chest" },
    [34] = { "@Spirit City/Below Cemetary/Chest" },
    [35] = { "@Spirit City/Banana Apartment/Chest" },
    [36] = { "@Spirit City/Abandon Homes/Green House Chest" },
    [37] = { "@Spirit City/Lone House/Chest" },

--Shady Sewers

    [61] = { "@Shady Sewers/Hidden Pipe Coins/Chest" },
    [62] = { "@Shady Sewers/Side Room/Chest" },
    [63] = { "@Shady Sewers/Rat Costume Room/Chest" },
    [64] = { "@Shady Sewers/Rat Costume Room/Chest" },
    [65] = { "@Shady Sewers/Rat Costume Room/Chest" },
    [66] = { "@Shady Sewers/Shady Gauntlet/Chest" },
    [67] = { "@Shady Sewers/Elf Merchant/Chest" },
    [68] = { "@Shady Sewers/Dr. Witch Doctor/Big Chest" },
    [69] = { "@Shady Sewers/Dr. Witch Doctor/Tutorial Chest" },

--Ghost Castle

    [91] = { "@Early Ghost Castle/Below Entrance/Chest" },
    [92] = { "@Early Ghost Castle/Slime Form Coins/Ground Chests" },
    [93] = { "@Early Ghost Castle/Slime Form Coins/Ground Chests" },
    [94] = { "@Early Ghost Castle/Slime Form Coins/Raised Chest" },
    [95] = { "@Ghost Castle/Flip Magic Platform/Chest" },
    [96] = { "@Ghost Castle/Hidden Ledge/Chest" },
    [97] = { "@Ghost Castle Rose Garden/Elf Merchant/Chest" },
    [98] = { "@Ghost Castle Rose Garden/Secret Garden Key/Chest" },
    [99] = { "@Top of Ghost Castle/Hidden Wall/Chest" },
    [100] = { "@Top of Ghost Castle/Along the Path/Chest" },
    [101] = { "@Top of Ghost Castle/Behind the Vines/Coins" },
    [102] = { "@Top of Ghost Castle/Hidden Shrub/Chest" },
    [103] = { "@Ghost Castle/Ghost Form/Big Chest" },
    [104] = { "@Ghost Castle Rose Garden/Thimble/Chest" },
    [105] = { "@Top of Ghost Castle/Ghost Boss/Chaos Key Piece" },

--Jigoku

    [121] = { "@Jigoku/Hidden Flip Magic Room/Chest" },
    [122] = { "@Jigoku/Slime Form Room/Chest" },
    [123] = { "@Jigoku/Early Ledge/Chest" },
    [124] = { "@Jigoku/Secret Spring Room/Hidden Chest" },
    [125] = { "@Jigoku/Beast's Key Chest/Chest" },
    [126] = { "@Jigoku/Hidden Ledge/Chest" },
    [127] = { "@Jigoku/Annahell/Chest" },
    [128] = { "@Jigoku/Hot Guy/Chest" },
    [129] = { "@Jigoku/Far Ledge/Chest" },
    [130] = { "@Jigoku/Hidden Flip Magic Ledge/Chest" },
    [131] = { "@Jigoku/Demon Wings Room/Big Chest" },
    [132] = { "@Jigoku/Demon Wings Room/Tutorial Chest" },
    [133] = { "@Jigoku/Northern Cat Shrine/Chest" },

--Club Demon

    [151] = { "@Club Demon/Club Demon Entrance/Chest" },
    [152] = { "@Club Demon/Under the Table/Hidden Chest" },
    [153] = { "@Club Demon/Club Door Room/Chest" },
    [154] = { "@Club Demon/Flip Magic Chest/Chest" },
    [155] = { "@Club Demon/Club Key Room/Chest" },
    [156] = { "@Club Demon/Demon Boss Key/Chest" },
    [157] = { "@Club Demon/Demon Boss/Chaos Key Piece" },

--Tengoku

    [181] = { "@Tengoku/Early Coins/Chest" },
    [182] = { "@Tengoku/Hidden Foliage/Chest" },
    [183] = { "@Upper Tengoku/Birby/Chest" },
    [184] = { "@Upper Tengoku/Flip Magic Coins/Chest" },
    [185] = { "@Upper Tengoku/Secret Alcove/Chest" },

--Angelic Hallway

    [211] = { "@Angelic Hallway/Starting Coins/Chest" },
    [212] = { "@Angelic Hallway/Elf Merchant/Chests" },
    [213] = { "@Angelic Hallway/Thimble/Chests" },
    [214] = { "@Angelic Hallway/Below Thimble/Chest" },
    [215] = { "@Angelic Hallway/Gabrielle/Chest" },
    [216] = { "@Angelic Hallway/Behind Vines/Chest" },
    [217] = { "@Angelic Hallway/Angel Feathers Room/Chest" },
    [218] = { "@Angelic Hallway/Below Boss Room/Chest" },
    [219] = { "@Angelic Hallway/Angelica/Chaos Key Piece" },

--Fungal Forest

    [241] = { "@Early Fungal Forest/Lower Pit/Chest" },
    [242] = { "@Early Fungal Forest/Past Chaos Fight/Chest" },
    [243] = { "@Fungal Forest/Closed Off Coins/Chest" },
    [244] = { "@Fungal Forest/Between the Thorns/Chest" },
    [245] = { "@Fungal Forest/Elf Merchant/Chest" },
    [246] = { "@Fungal Forest/Guarded by Mushrooms/Chest" },
    [247] = { "@Fungal Forest/Forgotten Fungal Door Key/Chest" },
    [248] = { "@Fungal Forest/Slime Form/Big Chest" },
    [249] = { "@Fungal Forest/Slime Citadel Key/Chest" },
    [250] = { "@Fungal Forest/Slime Form/Tutorial Chest" },

--Slime Citadel

    [271] = { "@Slime Citadel/Citadel Entrance/Chest" },
    [272] = { "@Slime Citadel/Secret Room/Chest" },
    [273] = { "@Slime Citadel/Lone Room/Chest" },
    [274] = { "@Slime Citadel/Slimy Sub Boss Key/Chest" },
    [275] = { "@Slime Citadel/Near Stone/Chest" },
    [276] = { "@Slime Citadel/Hidden Tunnel/Chest" },
    [277] = { "@Slime Citadel/Slurp/Slime Boss Key" },
    [278] = { "@Slime Citadel/Slimey Princess/Chaos Key Piece" },

--Umi Umi

    [301] = { "@Umi Umi/Save Coins/Chest" },
    [302] = { "@Umi Umi/Angler Costume/Chest" },
    [303] = { "@Umi Umi/Flip Magic Room/Chest" },
    [304] = { "@Umi Umi/Sacrificial Dagger/Chest" },
    [305] = { "@Umi Umi Depths/Mermaid's Chest/Chest" },
    [306] = { "@Umi Umi Depths/Chaos Fight Chest/Chest" },
    [307] = { "@Umi Umi Depths/Path to Octrina/Chest" },
    [308] = { "@Umi Umi Depths/Octrina/Chest" },
    [309] = { "@Umi Umi Depths/Frog Boss/Chaos Key Piece" },

--Chaos Castle

    [331] = { "@Castle Chaos/Early Coins/Chest" },
    [332] = { "@Castle Chaos/Jigoku Path/Chest" },
    [333] = { "@Castle Chaos/Near Chaos Sanctum/Chest" },
    [334] = { "@Castle Chaos/Elf Merchant/Chest" },
    [335] = { "@Castle Chaos/Slime Citadel Path/Chest" },
    [336] = { "@Castle Chaos/Big Jump/Chest" },
    [337] = { "@Castle Chaos/Pandora/Chaos Sanctum Key" },
    --[565] = { "@Castle Chaos/Chaos Queen/Done!" },

--Stats

    [361] = { "@Goblin Caves/Boss Key Room/HP Upgrade" },
    [362] = { "@Goblin Caves/Goblin Queen/MP Upgrade" },
    [363] = { "@Spirit City/Toilets/HP Upgrade" },
    [364] = { "@Spirit City/Toilets/MP Upgrade" },
    [365] = { "@Shady Sewers/Shady Gauntlet/HP Upgrade" },
    [366] = { "@Shady Sewers/Dr. Witch Doctor/MP Upgrade" },
    [367] = { "@Top of Ghost Castle/Ghost Boss/MP Upgrade" },
    [368] = { "@Top of Ghost Castle/Ghostly Gauntlet/HP Upgrade" },
    [369] = { "@Club Demon/Demonic Gauntlet/HP Upgrade" },
    [370] = { "@Club Demon/Demon Boss/MP Upgrade" },
    [371] = { "@Angelic Hallway/Angelic Gauntlet/HP Upgrade" },
    [372] = { "@Angelic Hallway/Angelica/MP Upgrade" },
    [373] = { "@Fungal Forest/Fungal Gauntlet/HP Upgrade" },
    [374] = { "@Early Fungal Forest/Past Fungella/MP Upgrade" },
    [375] = { "@Slime Citadel/Slimey Gauntlet/HP Upgrade" },
    [376] = { "@Slime Citadel/Slimey Princess/MP Upgrade" },
    [377] = { "@Umi Umi Depths/Watery Gauntlet/HP Upgrade" },
    [378] = { "@Umi Umi Depths/Frog Boss/MP Upgrade" },
    [379] = { "@Castle Chaos/Big Jump/HP Upgrade" },
    [380] = { "@Castle Chaos/Pandora/MP Upgrade" },

--Shops

    [401] = { "@Spirit City/Unmarked House/Fairy Bubble" },
    [402] = { "@Spirit City/Rare Items Shop/Shop Items" },
    [403] = { "@Spirit City/Rare Items Shop/Shop Items" },
    [404] = { "@Spirit City/Rare Items Shop/Shop Items" },
    [405] = { "@Spirit City/Rare Items Shop/Shop Items" },
    [406] = { "@Spirit City/Fashion Shop/Thimble" },
    [407] = { "@Spirit City/Fashion Shop/Thimble" },
    [408] = { "@Shady Sewers/Elf Merchant/Shop Items" },
    [409] = { "@Shady Sewers/Elf Merchant/Shop Items" },
    [410] = { "@Ghost Castle Rose Garden/Elf Merchant/Shop Item" },
    [411] = { "@Ghost Castle Rose Garden/Thimble/Shop Items" },
    [412] = { "@Ghost Castle Rose Garden/Thimble/Shop Items" },
    [413] = { "@Jigoku/Elf Merchant/Shop Items" },
    [414] = { "@Jigoku/Elf Merchant/Shop Items" },
    [415] = { "@Club Demon/Thimble/Shop Items" },
    [416] = { "@Club Demon/Thimble/Shop Items" },
    [417] = { "@Angelic Hallway/Elf Merchant/Shop Items" },
    [418] = { "@Angelic Hallway/Elf Merchant/Shop Items" },
    [419] = { "@Angelic Hallway/Thimble/Shop Items" },
    [420] = { "@Angelic Hallway/Thimble/Shop Items" },
    [421] = { "@Early Fungal Forest/Thimble/Shop Items" },
    [422] = { "@Early Fungal Forest/Thimble/Shop Items" },
    [423] = { "@Fungal Forest/Elf Merchant/Shop Items" },
    [424] = { "@Fungal Forest/Elf Merchant/Shop Items" },
    [425] = { "@Slime Citadel/Thimble/Shop Items" },
    [426] = { "@Slime Citadel/Thimble/Shop Items" },
    [427] = { "@Slime Citadel/Elf Merchant/Shop Items" },
    [428] = { "@Slime Citadel/Elf Merchant/Shop Items" },
    [429] = { "@Castle Chaos/Elf Merchant/Shop Item" },

--Quests

    [451] = { "@Witchy Woods/Beatrix/Magical Mentor & Bewitched Bubble" },
    [452] = { "B1" },
    [453] = { "@Witchy Woods/Mimi/Giant Chest Key" },
    [454] = { "G1" },
    [455] = { "@Goblin Caves/Flying Fairy/Fairy Mushrooms" },
    [456] = { "@Spirit City/MomoRobo/Out of Service" },
    [457] = { "@Spirit City/Bunny Club/The Bunny Club" },
    [458] = { "@Spirit City/Bunny Club/Find the Silky Slime" },
    [459] = { "MC1" },
    [460] = { "@Jigoku/Unlucky Cat/Unlucky Cat Statue" },
    [461] = { "@Jigoku/Annahell/Harvest Season" },
    [462] = { "@Angelic Hallway/Gabrielle/Long Distance Relationship" },
    [463] = { "@Slime Citadel/Natasha/Summoning Stones" },
    [464] = { "@Umi Umi Depths/Keroku/Seamen, With an A" },
    [465] = { "@Shady Sewers/Ratchel/Cardio Day" },
    [466] = { "@Spirit City/Ancient Being/Stop Democracy" },
    [467] = { "@Spirit City/Clinic/Medical Emergency" },
    [468] = { "R1" },
    [469] = { "B3" },
    [470] = { "MC2" },
    [471] = { "MC3" },
    [472] = { "@Spirit City/Cabaret Cafe/Ectogasm" },
    [473] = { "M1" },
    [474] = { "J1" },
    [475] = { "J2" },
    [476] = { "B2" },
    [477] = { "R2" },
    [478] = { "R3" },
    [479] = { "@Spirit City/Pig Mansion/Tatil's Tale" },
    [480] = { "@Spirit City/Pig Mansion/Signing Bonus" },
    [481] = { "G2" },
    [482] = { "@Spirit City/Leg's Office/Dirty Debut" },
    [483] = { "K1" },
    [484] = { "@Spirit City/Kyoni's Shop/What's a Daikon?" },
    [485] = { "@Spirit City/Dusty/Alley Cat" },
    [486] = { "@Spirit City/Cult of Whorus/Priestess of Whorus" },
    [487] = { "@Spirit City/Cult of Whorus/A Priest's Duties" },
    [488] = { "@Goblin Caves/Goblin Princess/Goblin Stud" },
    [489] = { "@Witchy Woods/Belle's Cowbell/Chest" },
    [490] = { "@Witchy Woods/Red Wine/Chest" },
    [491] = { "@Witchy Woods/Goblin Apartment/Gobliana's Luggage" },
    [492] = { "@Goblin Caves/Man Cave/Goblin Business Card" },
    [493] = { "@Goblin Caves/Gobliana/Goblin Headshot" },
    [494] = { "@Spirit City/Cabaret Cafe/Girl's Room Chest" },
    [495] = { "@Spirit City/Cabaret Cafe/Delicious Milk" },
    [496] = { "@Spirit City/Cabaret Cafe/Cherry Apt. Key" },
    [497] = { "@Spirit City/Cabaret Cafe/VIP Chest" },
    [498] = { "@Spirit City/Leg's Office/Goblin Apartment Key" },
    [499] = { "@Spirit City/MomoRobo/Server Password" },
    [500] = { "@Spirit City/Pig Mansion/Fungal Key" },
    [501] = { "@Spirit City/Pig Mansion/Maid Contract" },
    [502] = { "@Spirit City/Kyoni's Shop/Belle's Milkshake" },
    [503] = { "@Top of Ghost Castle/Willow the Whiff/Bundle of Clothes" },
    [504] = { "@Jigoku/Nearby Cat Shrine/Cat Shrine" },
    [505] = { "@Jigoku/Northern Cat Shrine/Cat Shrine" },
    [506] = { "@Club Demon/Club Demon Cat Shrine/Cat Shrine" },
    [507] = { "@Club Demon/Bad Boy/Demon Letter" },
    [508] = { "@Angelic Hallway/Cloudia/Chest" },
    [509] = { "@Angelic Hallway/Gabrielle/Angel Letter" },
    [510] = { "@Early Fungal Forest/Heavenly Daikon/Chest" },
    [511] = { "@Fungal Forest/Blue Jelly Mushroom/Chest" },
    [512] = { "@Early Fungal Forest/Fungella/Fungal Deed" },
    [513] = { "@Slime Citadel/Silky Slime/Chest" },
    [514] = { "@Slime Citadel/Silky Slime/Summoning Stone" },
    [515] = { "@Slime Citadel/Secret Room Past Spring/Summoning Stone" },
    [516] = { "@Slime Citadel/Slurp/Summoning Stone" },
    [517] = { "@Witchy Woods/Mimic Chest Key Room/Mimic Key" },
    [518] = { "@Spirit City/Abandon Homes/02 House Chest" },
    [519] = { "@Spirit City/Chaos Fight/Hellish Dango" },

--Sex Experience

    [551] = { "@Witchy Woods/Beatrix/Quest Upgrade 1" },
    [552] = { "@Witchy Woods/Beatrix/Quest Upgrade 2" },
    [553] = { "@Witchy Woods/Beatrix/Quest Upgrade 3" },
    [554] = { "@Witchy Woods/Beatrix/Quest Upgrade 4" },
    [555] = { "@Witchy Woods/Beatrix/Quest Upgrade 5" },
    [556] = { "@Witchy Woods/Beatrix/Quest Upgrade 6" },
    [557] = { "@Witchy Woods/Beatrix/Quest Upgrade 7" },
    [558] = { "@Witchy Woods/Beatrix/Quest Upgrade 8" },
    [559] = { "@Witchy Woods/Beatrix/Quest Upgrade 9" },
    [560] = { "@Witchy Woods/Beatrix/Quest Upgrade 10" },
    [561] = { "@Witchy Woods/Beatrix/Quest Upgrade 11" },
    [562] = { "@Witchy Woods/Beatrix/Quest Upgrade 12" },
    [563] = { "@Witchy Woods/Beatrix/Quest Upgrade 13" },
    [564] = { "@Witchy Woods/Beatrix/Quest Upgrade 14" },

--Gacha Rewards

    [601] = { "@Witchy Woods/Genesis/Special Promotion" },
    [602] = { "@Spirit City/Animal Gacha - Cabaret Cafe/Animal Gacha Pull 1" },
    [603] = { "@Spirit City/Animal Gacha - Cabaret Cafe/Animal Gacha Pull 2" },
    [604] = { "@Spirit City/Animal Gacha - Cabaret Cafe/Animal Gacha Pull 3" },
    [605] = { "@Spirit City/Animal Gacha - Cabaret Cafe/Animal Gacha Pull 4" },
    [606] = { "@Spirit City/Animal Gacha - Cabaret Cafe/Animal Gacha Pull 5" },
    [607] = { "@Spirit City/Animal Gacha - Cabaret Cafe/Animal Gacha Pull 6" },
    [608] = { "@Spirit City/Animal Gacha - Cabaret Cafe/Animal Gacha Pull 7" },
    [609] = { "@Spirit City/Animal Gacha - Cabaret Cafe/Animal Gacha Pull 8" },
    [610] = { "@Spirit City/Animal Gacha - Cabaret Cafe/Animal Gacha Pull 9" },
    [611] = { "@Spirit City/Animal Gacha - Cabaret Cafe/Animal Gacha Pull 10" },
    [612] = { "@Spirit City/Bunny Gacha - Kyoni's Shop/Bunny Gacha Pull 1" },
    [613] = { "@Spirit City/Bunny Gacha - Kyoni's Shop/Bunny Gacha Pull 2" },
    [614] = { "@Spirit City/Bunny Gacha - Kyoni's Shop/Bunny Gacha Pull 3" },
    [615] = { "@Spirit City/Bunny Gacha - Kyoni's Shop/Bunny Gacha Pull 4" },
    [616] = { "@Spirit City/Bunny Gacha - Kyoni's Shop/Bunny Gacha Pull 5" },
    [617] = { "@Spirit City/Bunny Gacha - Kyoni's Shop/Bunny Gacha Pull 6" },
    [618] = { "@Spirit City/Bunny Gacha - Kyoni's Shop/Bunny Gacha Pull 7" },
    [619] = { "@Spirit City/Bunny Gacha - Kyoni's Shop/Bunny Gacha Pull 8" },
    [620] = { "@Spirit City/Bunny Gacha - Kyoni's Shop/Bunny Gacha Pull 9" },
    [621] = { "@Spirit City/Bunny Gacha - Kyoni's Shop/Bunny Gacha Pull 10" },
    [622] = { "@Spirit City/Angel & Demon Gacha - Unmarked House/Angel & Demon Gacha Pull 1" },
    [623] = { "@Spirit City/Angel & Demon Gacha - Unmarked House/Angels & Demons Gacha Pull 2" },
    [624] = { "@Spirit City/Angel & Demon Gacha - Unmarked House/Angels & Demons Gacha Pull 3" },
    [625] = { "@Spirit City/Angel & Demon Gacha - Unmarked House/Angels & Demons Gacha Pull 4" },
    [626] = { "@Spirit City/Angel & Demon Gacha - Unmarked House/Angels & Demons Gacha Pull 5" },
    [627] = { "@Spirit City/Angel & Demon Gacha - Unmarked House/Angels & Demons Gacha Pull 6" },
    [628] = { "@Spirit City/Angel & Demon Gacha - Unmarked House/Angels & Demons Gacha Pull 7" },
    [629] = { "@Spirit City/Angel & Demon Gacha - Unmarked House/Angels & Demons Gacha Pull 8" },
    [630] = { "@Spirit City/Angel & Demon Gacha - Unmarked House/Angels & Demons Gacha Pull 9" },
    [631] = { "@Spirit City/Angel & Demon Gacha - Unmarked House/Angels & Demons Gacha Pull 10" },
    [632] = { "@Spirit City/Monster Gacha - Rare Items Shop/Monster Gacha Pull 1" },
    [633] = { "@Spirit City/Monster Gacha - Rare Items Shop/Monster Gacha Pull 2" },
    [634] = { "@Spirit City/Monster Gacha - Rare Items Shop/Monster Gacha Pull 3" },
    [635] = { "@Spirit City/Monster Gacha - Rare Items Shop/Monster Gacha Pull 4" },
    [636] = { "@Spirit City/Monster Gacha - Rare Items Shop/Monster Gacha Pull 5" },
    [637] = { "@Spirit City/Monster Gacha - Rare Items Shop/Monster Gacha Pull 6" },
    [638] = { "@Spirit City/Monster Gacha - Rare Items Shop/Monster Gacha Pull 7" },
    [639] = { "@Spirit City/Monster Gacha - Rare Items Shop/Monster Gacha Pull 8" },
    [640] = { "@Spirit City/Monster Gacha - Rare Items Shop/Monster Gacha Pull 9" },
    [641] = { "@Spirit City/Monster Gacha - Rare Items Shop/Monster Gacha Pull 10" },

--Gacha Coins


    [651] = { "@Witchy Woods/Genesis/Gacha Coin" },
    [652] = { "@Witchy Woods/Secret Cave/Gacha Coin" },
    [653] = { "@Witchy Woods/Rundown House/Gacha Coin Above Door" },
    [654] = { "@Witchy Woods/Secret Alcove/Gacha Coin" },
    [655] = { "@Goblin Caves/Post Fight/Gacha Coin" },
    [656] = { "@Goblin Caves/Hidden Spring Room/Gacha Coin" },
    [657] = { "@Witchy Woods/Before Great Fairy/Gacha Coin" },
    [658] = { "@Spirit City/Toilets/Gacha Coin" },
    [659] = { "@Spirit City/Behind Alley/Gacha Coin" },
    [660] = { "@Spirit City/Abandon Homes/01 House Gacha Coin" },
    [661] = { "@Spirit City/Abandon Homes/6 House Gacha Coin" },
    [662] = { "@Shady Sewers/Side Room/Gacha Coin" },
    [663] = { "@Shady Sewers/Ratchel/Gacha Coin" },
    [664] = { "@Top of Ghost Castle/Blind Jump/Gacha Coin" },
    [665] = { "@Ghost Castle/Up the Ladder/Gacha Coin" },
    [666] = { "@Top of Ghost Castle/Hidden Spring Room/Gacha Coin" },
    [667] = { "@Top of Ghost Castle/Across the Boss Room/Gacha Coin" },
    [668] = { "@Jigoku/Secret Spring Room/Gacha Coin" },
    [669] = { "@Jigoku/Hidden Hole/Gacha Coin" },
    [670] = { "@Jigoku/Near Elf Merchant/Gacha Coin" },
    [671] = { "@Jigoku/Northern Cat Shrine/Gacha Coin" },
    [672] = { "@Club Demon/Flip Magic Gacha Coin/Gacha Coin" },
    [673] = { "@Club Demon/Club Key Room/Gacha Coin" },
    [674] = { "@Tengoku/Early Gacha Coin/Gacha Coin" },
    [675] = { "@Upper Tengoku/Hidden Flip Magic Spring/Gacha Coin" },
    [676] = { "@Upper Tengoku/Hidden Ledge/Gacha Coin" },
    [677] = { "@Angelic Hallway/Hidden Foliage 1/Gacha Coin" },
    [678] = { "@Angelic Hallway/Hidden Foliage 2/Gacha Coin" },
    [679] = { "@Angelic Hallway/Flip Magic Room/Gacha Coin" },
    [680] = { "@Angelic Hallway/Below Boss Room/Gacha Coin" },
    [681] = { "@Early Fungal Forest/Flip Magic Gacha Coin/Gacha Coin" },
    [682] = { "@Fungal Forest/Secret Fungus Room/Gacha Coin" },
    [683] = { "@Slime Citadel/Small Detour/Gacha Coin" },
    [684] = { "@Slime Citadel/Across the Key/Gacha Coin" },
    [685] = { "@Slime Citadel/Secret Room Past Spring/Gacha Coin" },
    [686] = { "@Umi Umi/Early Gacha Coin/Gacha Coin" },
    [687] = { "@Umi Umi/Far Corner/Gacha Coin" },
    [688] = { "@Umi Umi/Flip Magic Room 2/Gacha Coin" },
    [689] = { "@Umi Umi Depths/Above Save Room/Gacha Coin" },
    [690] = { "@Umi Umi Depths/Path Near Frog Boss/Gacha Coin" },
    [691] = { "@Outside Castle Chaos/Outside Castle/Gacha Coin" },
    [692] = { "@Castle Chaos/Goblin/Fungal Path/Gacha Coin" },
    [693] = { "@Castle Chaos/Ghost Castle Path/Gacha Coin" },
    [694] = { "@Castle Chaos/Fungal Area/Gacha Coin" }

--[[Crystal Panels (waiting until they're properly added)
    [701] = {""},
    [702] = {""},
    [703] = {""},
    [704] = {""},
    [705] = {""},
    [706] = {""},
    [707] = {""},
    [708] = {""},
    [709] = {""},
    [710] = {""},
    [711] = {""},
    [712] = {""},
    [713] = {""},
    [714] = {""},
    [715] = {""},
    [716] = {""}
    ]]--
    
}
