-- use this file to map the AP location ids to your locations
-- to reference a location in Pop use @ in the beginning and then path to the section (more info: https://github.com/black-sliver/PopTracker/blob/master/doc/PACKS.md#locations)
-- to reference an item use it's code
-- here are the SM locations as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/location_mapping.lua
local base_id = 0

LOCATION_MAPPING = {
    [1] = { "@Sensei's Hut/Sensei's Hut/Chest" }, --"Sensei's Hut, Navy Witch Costume Chest"
    [2] = { "@Sensei's Hut/Sensei's Hut/Chest Behind Laser" },
    [3] = { "@Sensei's Hut/Past the Hut/Peachy Peaches" },
    [4] = { "@Above the Goblin Camp/Rundown House Save/Hidden Chest" },
    [5] = { "@Goblin Tower/Waterfall Save/Chest" },
    [6] = { "@Sensei's Hut/Secret Cave/Chest" },
    [7] = { "@Goblin Camp Middle/Mimi's Room/Hidden Chest" },
    [8] = { "@Goblin Tower/Rundown House/Chest Behind Door" },
    [9] = { "@Goblin Caves/Past Man Cave/Chest" },
    [10] = { "@Goblin Caves/Gerry G. Atric/Chest" },
    [11] = { "@Goblin Caves/Hidden Alcove/Chest" },
    [12] = { "@Goblin Caves/Beside Flip Magic Platform/Chest" },
    [13] = { "@Goblin Caves/After Chaos Fight/Chest" },
    [14] = { "@Goblin Caves/Boss Key Room/Chest" },
    [15] = { "@Goblin Caves/Boss Key Room/Big Chest" },
    [16] = { "@Goblin Caves/Goblin Queen/Chaos Key Piece" },
    [17] = { "@Goblin Caves/Flying Fairy Room/Chest" },
    [18] = { "@Goblin Tower/Great Fairy/Fairy Reward" },

--Spirit City

    [31] = { "@Spirit City/Rare Items Shop Roof/Chest" },
    [32] = { "@Spirit City/Ancient Being Chest/Chest" },
    [33] = { "@Spirit City/Ghostly Castle Key/Chest" },
    [34] = { "@Spirit City/Below Cemetary/Chest" },
    [35] = { "@Spirit City/Banana Apartment/Chest" },
    [36] = { "@East Spirit City/Green House/Chest" },
    [37] = { "@East Spirit City/Lone House/Chest" },

--Shady Sewers

    [61] = { "@Shady Sewers/Hidden Pipe Coins/Chest" },
    [62] = { "@Shady Sewers/Side Room/Chest" },
    [63] = { "@Shady Sewers/Rat Costume Room/Chest" },
    [64] = { "@Shady Sewers/Rat Costume Room/Chest" },
    [65] = { "@Shady Sewers/Rat Costume Room/Chest" },
    [66] = { "@Shady Sewers/Shady Gauntlet/Chest" },
    [67] = { "@Shady Sewers/Elf Merchant Chest/Chest" },
    [68] = { "@Shady Sewers/Dr. Witch Doctor/Big Chest" },
    [69] = { "@Shady Sewers/Dr. Witch Doctor/Tutorial Chest" },

--Ghost Castle

    [91] = { "@East Spirit City/Below Entrance/Chest" },
    [92] = { "@Early Ghost Castle/Slime Form Coins/Ground Chests" },
    [93] = { "@Early Ghost Castle/Slime Form Coins/Ground Chests" },
    [94] = { "@Early Ghost Castle/Slime Form Coins/Raised Chest" },
    [95] = { "@Early Ghost Castle/Flip Magic Platform/Chest" },
    [96] = { "@Early Ghost Castle/Hidden Ledge/Chest" },
    [97] = { "@Rose Garden/Elf Merchant Chest/Chest" },
    [98] = { "@Rose Garden/Secret Garden Key/Chest" },
    [99] = { "@Top of Ghost Castle/Hidden Wall/Chest" },
    [100] = { "@Top of Ghost Castle/Along the Path/Chest" },
    [101] = { "@Top of Ghost Castle/Behind the Vines/Coins" },
    [102] = { "@Top of Ghost Castle/Hidden Shrub/Chest" },
    [103] = { "@Tall Tower/Ghost Form/Big Chest" },
    [104] = { "@Thimble Ghost Castle/Thimble Chest/Chest" },
    [105] = { "@Top of Ghost Castle/Ghost Boss/Chaos Key Piece" },

--Jigoku

    [121] = { "@Early Jigoku/Hidden Flip Magic Room/Chest" },
    [122] = { "@Early Jigoku/Slime Form Room/Chest" },
    [123] = { "@Early Jigoku/Early Ledge/Chest" },
    [124] = { "@Early Jigoku/Secret Spring Room/Hidden Chest" },
    [125] = { "@Lower Jigoku/Beast's Key Chest/Chest" },
    [126] = { "@Lower Jigoku/Hidden Ledge/Chest" },
    [127] = { "@East Jigoku/Across Annahell/Chest" },
    [128] = { "@East Jigoku/Hot Guy/Chest" },
    [129] = { "@East Jigoku/Far Ledge/Chest" },
    [130] = { "@East Jigoku/Hidden Flip Magic Ledge/Chest" },
    [131] = { "@East Jigoku/Demon Wings Room/Big Chest" },
    [132] = { "@East Jigoku/Demon Wings Room/Tutorial Chest" },
    [133] = { "@East Jigoku/Northern Cat Shrine Chest/Chest" },

--Club Demon

    [151] = { "@Club Demon/Club Demon Entrance/Chest" },
    [152] = { "@Club Demon/Under the Table/Hidden Chest" },
    [153] = { "@Club Demon/Club Door Room/Chest" },
    [154] = { "@Club Demon/Flip Magic Chest/Chest" },
    [155] = { "@Club Demon/Club Key Room/Chest" },
    [156] = { "@Club Demon/Demon Boss Key/Chest" },
    [157] = { "@Club Demon/Demon Boss/Chaos Key Piece" },

--Tengoku

    [181] = { "@Early Tengoku/Early Coins/Chest" },
    [182] = { "@Early Tengoku/Hidden Foliage/Chest" },
    [183] = { "@Mid Tengoku/Birby/Chest" },
    [184] = { "@Mid Tengoku/Flip Magic Coins/Chest" },
    [185] = { "@Tengoku/Secret Alcove/Chest" },

--Angelic Hallway

    [211] = { "@Tengoku/Starting Coins/Chest" },
    [212] = { "@Merchant Angelic/Elf Merchant Chest/Chest" },
    [213] = { "@Angelic Hallway/Thimble Chest/Chest" },
    [214] = { "@Angelic Hallway/Below Thimble/Chest" },
    [215] = { "@Angelic Hallway/Across Gabrielle/Chest" },
    [216] = { "@Angelic Hallway/Behind Vines/Chest" },
    [217] = { "@Angelic Hallway/Angel Feathers Room/Chest" },
    [218] = { "@Angelica Angelic/Below Boss Room/Chest" },
    [219] = { "@Angelica Angelic/Angelica/Chaos Key Piece" },

--Fungal Forest

    [241] = { "@Early Fungal Forest/Lower Pit/Chest" },
    [242] = { "@Chaos Fungal/Past Chaos Fight/Chest" },
    [243] = { "@Fungal Forest/Closed Off Coins/Chest" },
    [244] = { "@Deep Fungal/Between the Thorns/Chest" },
    [245] = { "@Deep Fungal/Elf Merchant Chest/Chest" },
    [246] = { "@Deep Fungal/Guarded by Mushrooms/Chest" },
    [247] = { "@Deep Fungal/Forgotten Fungal Door Key/Chest" },
    [248] = { "@Deep Fungal/Slime Form/Big Chest" },
    [249] = { "@Deep Fungal/Slime Citadel Key/Chest" },
    [250] = { "@Deep Fungal/Slime Form/Tutorial Chest" },

--Slime Citadel

    [271] = { "@Slime Citadel/Citadel Entrance/Chest" },
    [272] = { "@Slime Citadel/Secret Room/Chest" },
    [273] = { "@Slime Citadel/Lone Room/Chest" },
    [274] = { "@Slime Citadel/Slimy Sub Boss Key/Chest" },
    [275] = { "@Slime Citadel/Near Stone/Chest" },
    [276] = { "@Slime Citadel/Hidden Tunnel/Chest" },
    [277] = { "@Slime Citadel/Slurp/Slime Boss Key" },
    [278] = { "@Slime Citadel/Slimey Princess/Chaos Key Piece" },

--Umi Umi

    [301] = { "@Umi Umi/Save Coins/Chest" },
    [302] = { "@Umi Umi/Angler Costume/Chest" },
    [303] = { "@Umi Umi/Flip Magic Room/Chest" },
    [304] = { "@Umi Umi/Sacrificial Dagger/Chest" },
    [305] = { "@Umi Umi/Mermaid's Chest/Chest" },
    [306] = { "@Umi Umi/Chaos Fight Chest/Chest" },
    [307] = { "@Umi Umi/Path to Octrina/Chest" },
    [308] = { "@Umi Umi/Octrina/Chest" },
    [309] = { "@Umi Umi/Frog Boss/Chaos Key Piece" },

--Chaos Castle

    [331] = { "@Castle Chaos/Early Coins/Chest" },
    [332] = { "@Castle Chaos/Jigoku Path/Chest" },
    [333] = { "@Castle Chaos/Near Chaos Sanctum/Chest" },
    [334] = { "@Castle Chaos/Elf Merchant Chest/Chest" },
    [335] = { "@Castle Chaos/Slime Citadel Path/Chest" },
    [336] = { "@Castle Chaos/Big Jump/Chest" },
    [337] = { "@Castle Chaos/Pandora/Chaos Sanctum Key" },
    --[565] = { "@Castle Chaos/Chaos Queen/Done!" },

--Stats

    [361] = { "@Goblin Caves/Boss Key Room Upgrade/HP Upgrade" },
    [362] = { "@Goblin Caves/Goblin Queen Upgrade/MP Upgrade" },
    [363] = { "@Spirit City/Toilets/HP Upgrade" },
    [364] = { "@Spirit City/Toilets/MP Upgrade" },
    [365] = { "@Shady Sewers/Shady Gauntlet Upgrade/HP Upgrade" },
    [366] = { "@Shady Sewers/Dr. Witch Doctor Upgrade/MP Upgrade" },
    [367] = { "@Top of Ghost Castle/Ghost Boss Upgrade/MP Upgrade" },
    [368] = { "@Top of Ghost Castle/Ghostly Gauntlet/HP Upgrade" },
    [369] = { "@Club Demon/Demonic Gauntlet/HP Upgrade" },
    [370] = { "@Club Demon/Demon Boss Upgrade/MP Upgrade" },
    [371] = { "@Angelic Hallway/Angelic Gauntlet/HP Upgrade" },
    [372] = { "@Angelica Angelic/Angelica Upgrade/MP Upgrade" },
    [373] = { "@Fungal Forest/Fungal Gauntlet/HP Upgrade" },
    [374] = { "@Early Fungal Forest/Past Fungella/MP Upgrade" },
    [375] = { "@Slime Citadel/Slimey Gauntlet/HP Upgrade" },
    [376] = { "@Slime Citadel/Slimey Princess Upgrade/MP Upgrade" },
    [377] = { "@Umi Umi/Watery Gauntlet/HP Upgrade" },
    [378] = { "@Umi Umi/Frog Boss Upgrade/MP Upgrade" },
    [379] = { "@Castle Chaos/Big Jump Upgrade/HP Upgrade" },
    [380] = { "@Castle Chaos/Pandora Upgrade/MP Upgrade" },

--Shops

    [401] = { "@Spirit City/Unmarked House/Fairy Bubble" },
    [402] = { "@Spirit City/Rare Items Shop/Shop Item 1" },
    [403] = { "@Spirit City/Rare Items Shop/Shop Item 2" },
    [404] = { "@Spirit City/Rare Items Shop/Shop Item 3" },
    [405] = { "@Spirit City/Rare Items Shop/Shop Item 4" },
    [406] = { "@Spirit City/Fashion Shop/Store Item 1" },
    [407] = { "@Spirit City/Fashion Shop/Store Item 2" },
    [408] = { "@Shady Sewers/Elf Merchant/Shop Item 1" },
    [409] = { "@Shady Sewers/Elf Merchant/Shop Item 2" },
    [410] = { "@Rose Garden/Elf Merchant/Shop Item" },
    [411] = { "@Thimble Ghost Castle/Thimble/Shop Item 1" },
    [412] = { "@Thimble Ghost Castle/Thimble/Shop Item 2" },
    [413] = { "@East Jigoku/Elf Merchant/Shop Item 1" },
    [414] = { "@East Jigoku/Elf Merchant/Shop Item 2" },
    [415] = { "@Club Demon/Thimble/Shop Item 1" },
    [416] = { "@Club Demon/Thimble/Shop Item 2" },
    [417] = { "@Merchant Angelic/Elf Merchant/Shop Item 1" },
    [418] = { "@Merchant Angelic/Elf Merchant/Shop Item 2" },
    [419] = { "@Angelic Hallway/Thimble/Shop Item 1" },
    [420] = { "@Angelic Hallway/Thimble/Shop Item 2" },
    [421] = { "@Early Fungal Forest/Fungal Thimble/Shop Item 1" },
    [422] = { "@Early Fungal Forest/Fungal Thimble/Shop Item 2" },
    [423] = { "@Deep Fungal/Elf Merchant/Shop Item 1" },
    [424] = { "@Deep Fungal/Elf Merchant/Shop Item 2" },
    [425] = { "@Slime Citadel/Thimble/Shop Item 1" },
    [426] = { "@Slime Citadel/Thimble/Shop Item 2" },
    [427] = { "@Slime Citadel/Elf Merchant/Shop Item 1" },
    [428] = { "@Slime Citadel/Elf Merchant/Shop Item 2" },
    [429] = { "@Castle Chaos/Elf Merchant/Shop Item" },

--Quests

    [451] = { "@Sensei's Hut/Beatrix/Magical Mentor & Bewitched Bubble" },
    [452] = { "B1" },
    [453] = { "@Goblin Camp Middle/Mimi/Giant Chest Key" },
    [454] = { "G1" },
    [455] = { "@Goblin Caves/Flying Fairy/Fairy Mushrooms" },
    [456] = { "@Spirit City/MomoRobo/Out of Service" },
    [457] = { "@Spirit City/Bunny Club/The Bunny Club" },
    [458] = { "@Spirit City/Bunny Club/Find the Silky Slime" },
    [459] = { "MC1" },
    [460] = { "@Lower Jigoku/Unlucky Cat/Unlucky Cat Statue" },
    [461] = { "@Lower Jigoku/Annahell/Harvest Season" },
    [462] = { "@Angelic Hallway/Gabrielle/Long Distance Relationship" },
    [463] = { "@Slime Citadel/Natasha/Summoning Stones" },
    [464] = { "@Umi Umi/Keroku/Seamen, With an A" },
    [465] = { "@Shady Sewers/Ratchel/Cardio Day" },
    [466] = { "@Spirit City/Ancient Being/Stop Democracy" },
    [467] = { "@Spirit City/Clinic/Medical Emergency" },
    [468] = { "R1" },
    [469] = { "B3" },
    [470] = { "MC2" },
    [471] = { "MC3" },
    [472] = { "@Spirit City/Cabaret Cafe/Ectogasm" },
    [473] = { "M1" },
    [474] = { "J1" },
    [475] = { "J2" },
    [476] = { "B2" },
    [477] = { "R2" },
    [478] = { "R3" },
    [479] = { "@East Spirit City/Pig Mansion/Tatil's Tale" },
    [480] = { "@East Spirit City/Pig Mansion/Signing Bonus" },
    [481] = { "G2" },
    [482] = { "@Spirit City/Leg's Office/Dirty Debut" },
    [483] = { "K1" },
    [484] = { "@Spirit City/Kyoni's Shop/What's a Daikon?" },
    [485] = { "@Spirit City/Dusty/Alley Cat" },
    [486] = { "@Spirit City/Cult of Whorus/Priestess of Whorus" },
    [487] = { "@Spirit City/Cult of Whorus/A Priest's Duties" },
    [488] = { "@Goblin Caves/Goblin Princess/Goblin Stud" },
    [489] = { "@Goblin Tower/Belle's Cowbell/Chest" },
    [490] = { "@Goblin Tower/Red Wine/Chest" },
    [491] = { "@Goblin Tower/Goblin Apartment/Gobliana's Luggage" },
    [492] = { "@Goblin Caves/Man Cave/Goblin Business Card" },
    [493] = { "@Goblin Caves/Gobliana/Goblin Headshot" },
    [494] = { "@Spirit City/Cabaret Cafe/Girl's Room Chest" },
    [495] = { "@Spirit City/Cabaret Cafe/Delicious Milk" },
    [496] = { "@Spirit City/Cabaret Cafe/Cherry Apt. Key" },
    [497] = { "@Spirit City/Cabaret Cafe/VIP Chest" },
    [498] = { "@Spirit City/Leg's Office/Goblin Apartment Key" },
    [499] = { "@Spirit City/MomoRobo/Server Password" },
    [500] = { "@East Spirit City/Pig Mansion/Fungal Key" },
    [501] = { "@East Spirit City/Pig Mansion/Maid Contract" },
    [502] = { "@Spirit City/Kyoni's Shop/Belle's Milkshake" },
    [503] = { "@Top of Ghost Castle/Willow the Whiff/Bundle of Clothes" },
    [504] = { "@Lower Jigoku/Nearby Cat Shrine/Cat Shrine" },
    [505] = { "@East Jigoku/Northern Cat Shrine/Cat Shrine" },
    [506] = { "@Club Demon/Club Demon Cat Shrine/Cat Shrine" },
    [507] = { "@Club Demon/Bad Boy/Demon Letter" },
    [508] = { "@Angelic Hallway/Cloudia/Chest" },
    [509] = { "@Angelic Hallway/Gabrielle/Angel Letter" },
    [510] = { "@Early Fungal Forest/Heavenly Daikon/Chest" },
    [511] = { "@Fungal Forest/Blue Jelly Mushroom/Chest" },
    [512] = { "@Early Fungal Forest/Fungella/Fungal Deed" },
    [513] = { "@Slime Citadel/Silky Slime/Chest" },
    [514] = { "SS1" },
    [515] = { "SS2" },
    [516] = { "SS3" },
    [517] = { "@Goblin Tower/Waterfall Save Key/Mimic Key" },
    [518] = { "@East Spirit City/02 House/Chest" },
    [519] = { "@Spirit City/Chaos Fight/Hellish Dango" },

--Sex Experience

    [551] = { "@Sensei's Hut/Beatrix/Quest Upgrade 1" },
    [552] = { "@Sensei's Hut/Beatrix/Quest Upgrade 2" },
    [553] = { "@Sensei's Hut/Beatrix/Quest Upgrade 3" },
    [554] = { "@Sensei's Hut/Beatrix/Quest Upgrade 4" },
    [555] = { "@Sensei's Hut/Beatrix/Quest Upgrade 5" },
    [556] = { "@Sensei's Hut/Beatrix/Quest Upgrade 6" },
    [557] = { "@Sensei's Hut/Beatrix/Quest Upgrade 7" },
    [558] = { "@Sensei's Hut/Beatrix/Quest Upgrade 8" },
    [559] = { "@Sensei's Hut/Beatrix/Quest Upgrade 9" },
    [560] = { "@Sensei's Hut/Beatrix/Quest Upgrade 10" },
    [561] = { "@Sensei's Hut/Beatrix/Quest Upgrade 11" },
    [562] = { "@Sensei's Hut/Beatrix/Quest Upgrade 12" },
    [563] = { "@Sensei's Hut/Beatrix/Quest Upgrade 13" },
    [564] = { "@Sensei's Hut/Beatrix/Quest Upgrade 14" },

--Gacha Rewards

    [601] = { "@Above the Goblin Camp/Genesis/Special Promotion" },
    [602] = { "@Spirit City/Animal Gacha - Cabaret Cafe/Animal Gacha Pull 1" },
    [603] = { "@Spirit City/Animal Gacha - Cabaret Cafe/Animal Gacha Pull 2" },
    [604] = { "@Spirit City/Animal Gacha - Cabaret Cafe/Animal Gacha Pull 3" },
    [605] = { "@Spirit City/Animal Gacha - Cabaret Cafe/Animal Gacha Pull 4" },
    [606] = { "@Spirit City/Animal Gacha - Cabaret Cafe/Animal Gacha Pull 5" },
    [607] = { "@Spirit City/Animal Gacha - Cabaret Cafe/Animal Gacha Pull 6" },
    [608] = { "@Spirit City/Animal Gacha - Cabaret Cafe/Animal Gacha Pull 7" },
    [609] = { "@Spirit City/Animal Gacha - Cabaret Cafe/Animal Gacha Pull 8" },
    [610] = { "@Spirit City/Animal Gacha - Cabaret Cafe/Animal Gacha Pull 9" },
    [611] = { "@Spirit City/Animal Gacha - Cabaret Cafe/Animal Gacha Pull 10" },
    [612] = { "@Spirit City/Bunny Gacha - Kyoni's Shop/Bunny Gacha Pull 1" },
    [613] = { "@Spirit City/Bunny Gacha - Kyoni's Shop/Bunny Gacha Pull 2" },
    [614] = { "@Spirit City/Bunny Gacha - Kyoni's Shop/Bunny Gacha Pull 3" },
    [615] = { "@Spirit City/Bunny Gacha - Kyoni's Shop/Bunny Gacha Pull 4" },
    [616] = { "@Spirit City/Bunny Gacha - Kyoni's Shop/Bunny Gacha Pull 5" },
    [617] = { "@Spirit City/Bunny Gacha - Kyoni's Shop/Bunny Gacha Pull 6" },
    [618] = { "@Spirit City/Bunny Gacha - Kyoni's Shop/Bunny Gacha Pull 7" },
    [619] = { "@Spirit City/Bunny Gacha - Kyoni's Shop/Bunny Gacha Pull 8" },
    [620] = { "@Spirit City/Bunny Gacha - Kyoni's Shop/Bunny Gacha Pull 9" },
    [621] = { "@Spirit City/Bunny Gacha - Kyoni's Shop/Bunny Gacha Pull 10" },
    [622] = { "@Spirit City/Angel & Demon Gacha - Unmarked House/Angel & Demon Gacha Pull 1" },
    [623] = { "@Spirit City/Angel & Demon Gacha - Unmarked House/Angels & Demons Gacha Pull 2" },
    [624] = { "@Spirit City/Angel & Demon Gacha - Unmarked House/Angels & Demons Gacha Pull 3" },
    [625] = { "@Spirit City/Angel & Demon Gacha - Unmarked House/Angels & Demons Gacha Pull 4" },
    [626] = { "@Spirit City/Angel & Demon Gacha - Unmarked House/Angels & Demons Gacha Pull 5" },
    [627] = { "@Spirit City/Angel & Demon Gacha - Unmarked House/Angels & Demons Gacha Pull 6" },
    [628] = { "@Spirit City/Angel & Demon Gacha - Unmarked House/Angels & Demons Gacha Pull 7" },
    [629] = { "@Spirit City/Angel & Demon Gacha - Unmarked House/Angels & Demons Gacha Pull 8" },
    [630] = { "@Spirit City/Angel & Demon Gacha - Unmarked House/Angels & Demons Gacha Pull 9" },
    [631] = { "@Spirit City/Angel & Demon Gacha - Unmarked House/Angels & Demons Gacha Pull 10" },
    [632] = { "@Spirit City/Monster Gacha - Rare Items Shop/Monster Gacha Pull 1" },
    [633] = { "@Spirit City/Monster Gacha - Rare Items Shop/Monster Gacha Pull 2" },
    [634] = { "@Spirit City/Monster Gacha - Rare Items Shop/Monster Gacha Pull 3" },
    [635] = { "@Spirit City/Monster Gacha - Rare Items Shop/Monster Gacha Pull 4" },
    [636] = { "@Spirit City/Monster Gacha - Rare Items Shop/Monster Gacha Pull 5" },
    [637] = { "@Spirit City/Monster Gacha - Rare Items Shop/Monster Gacha Pull 6" },
    [638] = { "@Spirit City/Monster Gacha - Rare Items Shop/Monster Gacha Pull 7" },
    [639] = { "@Spirit City/Monster Gacha - Rare Items Shop/Monster Gacha Pull 8" },
    [640] = { "@Spirit City/Monster Gacha - Rare Items Shop/Monster Gacha Pull 9" },
    [641] = { "@Spirit City/Monster Gacha - Rare Items Shop/Monster Gacha Pull 10" },

--Gacha Coins


    [651] = { "@Above the Goblin Camp/Genesis/Gacha Coin" },
    [652] = { "@Sensei's Hut/Secret Cave Coin/Gacha Coin" },
    [653] = { "@Above the Goblin Camp/Rundown House Coin/Gacha Coin Above Door" },
    [654] = { "@Goblin Tower/Secret Alcove/Gacha Coin" },
    [655] = { "@Goblin Caves/Post Fight/Gacha Coin" },
    [656] = { "@Goblin Caves/Hidden Spring Room/Gacha Coin" },
    [657] = { "@Goblin Tower/Before Great Fairy/Gacha Coin" },
    [658] = { "@Spirit City/Above Toilets/Gacha Coin" },
    [659] = { "@Spirit City/Behind Alley/Gacha Coin" },
    [660] = { "@East Spirit City/01 House/Gacha Coin" },
    [661] = { "@East Spirit City/6 House/Gacha Coin" },
    [662] = { "@Shady Sewers/Side Room Coin/Gacha Coin" },
    [663] = { "@Shady Sewers/Ratchel Coin/Gacha Coin" },
    [664] = { "@Top of Ghost Castle/Blind Jump/Gacha Coin" },
    [665] = { "@Early Ghost Castle/Up the Ladder/Gacha Coin" },
    [666] = { "@Top of Ghost Castle/Hidden Spring Room/Gacha Coin" },
    [667] = { "@Top of Ghost Castle/Across the Boss Room/Gacha Coin" },
    [668] = { "@Early Jigoku/Secret Spring Room Coin/Gacha Coin" },
    [669] = { "@East Jigoku/Hidden Hole/Gacha Coin" },
    [670] = { "@East Jigoku/Near Elf Merchant/Gacha Coin" },
    [671] = { "@East Jigoku/Northern Cat Shrine Coin/Gacha Coin" },
    [672] = { "@Club Demon/Flip Magic Gacha Coin/Gacha Coin" },
    [673] = { "@Club Demon/Club Key Room Coin/Gacha Coin" },
    [674] = { "@Early Tengoku/Early Gacha Coin/Gacha Coin" },
    [675] = { "@Mid Tengoku/Hidden Flip Magic Spring/Gacha Coin" },
    [676] = { "@Mid Tengoku/Hidden Ledge/Gacha Coin" },
    [677] = { "@Early Angelic/Hidden Foliage 1/Gacha Coin" },
    [678] = { "@Angelic Hallway/Hidden Foliage 2/Gacha Coin" },
    [679] = { "@Angelic Hallway/Flip Magic Room/Gacha Coin" },
    [680] = { "@Angelica Angelic/Below Boss Room Coin/Gacha Coin" },
    [681] = { "@Early Fungal Forest/Flip Magic Gacha Coin/Gacha Coin" },
    [682] = { "@Deep Fungal/Secret Fungus Room/Gacha Coin" },
    [683] = { "@Slime Citadel/Small Detour/Gacha Coin" },
    [684] = { "@Slime Citadel/Across the Key/Gacha Coin" },
    [685] = { "@Slime Citadel/Secret Room Past Spring Coin/Gacha Coin" },
    [686] = { "@Umi Umi/Early Gacha Coin/Gacha Coin" },
    [687] = { "@Umi Umi/Far Corner/Gacha Coin" },
    [688] = { "@Umi Umi/Flip Magic Room 2/Gacha Coin" },
    [689] = { "@Umi Umi/Above Save Room/Gacha Coin" },
    [690] = { "@Umi Umi/Path Near Frog Boss/Gacha Coin" },
    [691] = { "@Castle Chaos/Outside Castle/Gacha Coin" },
    [692] = { "@Castle Chaos/Goblin/Fungal Path/Gacha Coin" },
    [693] = { "@Castle Chaos/Ghost Castle Path/Gacha Coin" },
    [694] = { "@Castle Chaos/Fungal Area/Gacha Coin" },

--Crystal Teleporters
    [701] = {"@Sensei's Hut/Sensei's Hut/Crystal Teleporter"},
    [702] = {"@Spirit City/Witchy Woods/Crystal Teleporter"},
    [703] = {"@Goblin Caves/Goblin Caves/Crystal Teleporter"},
    [704] = {"@Spirit City/Spirit City/Crystal Teleporter"},
    [705] = {"@Spirit City/Shady Alley/Crystal Teleporter"},
    [706] = {"@East Spirit City/Ghost Castle Entrance/Crystal Teleporter"},
    [707] = {"@Thimble Ghost Castle/Ghost Castle/Crystal Teleporter"},
    [708] = {"@Early Jigoku/Jigoku/Crystal Teleporter"},
    [709] = {"@Club Demon/Club Demon/Crystal Teleporter"},
    [710] = {"@Tengoku/Tengoku/Crystal Teleporter"},
    [711] = {"@Angelic Hallway/Angelic Hallway/Crystal Teleporter"},
    [712] = {"@Early Fungal Forest/Fungal Forest/Crystal Teleporter"},
    [713] = {"@Slime Citadel/Slime Citadel/Crystal Teleporter"},
    [714] = {"@Slime Citadel/Slimy Depths/Crystal Teleporter"},
    [715] = {"@Umi Umi/Umi Umi/Crystal Teleporter"},

--Pot Locations
    [751] = {"@Above the Goblin Camp/Goblin Camp Pots/Pots"},
    [752] = {"@Above the Goblin Camp/Goblin Camp Pots/Pots"},
    [753] = {"@Goblin Tower/Goblin Tower Pots/Pots"},
    [754] = {"@Goblin Tower/Goblin Tower Pots/Pots"},
    [755] = {"@Goblin Tower/Goblin Tower Pots/Pots"},
    [756] = {"@Goblin Tower/Goblin Tower Pots/Pots"},
    [757] = {"@Goblin Tower/Goblin Stairwell Pots/Pots"},
    [758] = {"@Goblin Tower/Goblin Stairwell Pots/Pots"},
    [759] = {"@Goblin Tower/Goblin Stairwell Pots/Pots"},
    [760] = {"@Goblin Tower/Man Cave Entrance Pots/Pots"},
    [761] = {"@Goblin Tower/Man Cave Entrance Pots/Pots"},
    [762] = {"@Goblin Caves/Cavern Stairs Pots/Pots"},
    [763] = {"@Goblin Caves/Cavern Stairs Pots/Pots"},
    [764] = {"@Goblin Caves/Cavern Stairs Pots/Pots"},
    [765] = {"@Goblin Caves/Cavern Stairs Pots/Pots"},
    [766] = {"@Goblin Caves/Cavern Stairs Pots/Pots"},
    [767] = {"@Goblin Caves/Cavern Stairs Pots/Pots"},
    [768] = {"@Goblin Caves/Ramp Pots/Pots"},
    [769] = {"@Goblin Caves/Ramp Pots/Pots"},
    [770] = {"@Goblin Caves/Ramp Pots/Pots"},
    [771] = {"@Goblin Caves/Ramp Pots/Pots"},
    [772] = {"@Goblin Caves/Descent Pots/Pots"},
    [773] = {"@Goblin Caves/Descent Pots/Pots"},
    [774] = {"@Goblin Caves/Descent Pots/Pots"},
    [775] = {"@Goblin Caves/Descent Pots/Pots"},
    [776] = {"@Goblin Caves/Descent Pots/Pots"},
    [777] = {"@Goblin Caves/Descent Pots/Pots"},
    [778] = {"@Goblin Caves/Goblin Queen Pots/Pots"},
    [779] = {"@Goblin Caves/Goblin Queen Pots/Pots"},
    [780] = {"@Goblin Caves/Goblin Queen Pots/Pots"},
    [781] = {"@Goblin Caves/Goblin Queen Pots/Pots"},
    [782] = {"@Goblin Tower/Fairy Entrance Pots/Pots"},
    [783] = {"@Goblin Tower/Fairy Entrance Pots/Pots"},
    [784] = {"@Goblin Tower/Fairy Entrance Pots/Pots"},
    [785] = {"@Goblin Tower/Fairy Entrance Pots/Pots"},
    [786] = {"@Spirit City/Spirit City Bridge Pots/Pots"},
    [787] = {"@Spirit City/Spirit City Bridge Pots/Pots"},
    [788] = {"@Spirit City/Spirit City Bridge Pots/Pots"},
    [789] = {"@Spirit City/Waterfall Tomb Pots/Pots"},
    [790] = {"@Spirit City/Waterfall Tomb Pots/Pots"},
    [791] = {"@Spirit City/Waterfall Tomb Pots/Pots"},
    [792] = {"@Spirit City/Waterfall Tomb Pots/Pots"},
    [793] = {"@Spirit City/Cabaret Cafe/Wizard Toilet Pots"},
    [794] = {"@Spirit City/Cabaret Cafe/Wizard Toilet Pots"},
    [795] = {"@Spirit City/Cabaret Cafe/Wizard Toilet Pots"},
    [796] = {"@East Spirit City/Green House/Pots"},
    [797] = {"@East Spirit City/Green House/Pots"},
    [798] = {"@East Spirit City/Green House/Pots"},
    [799] = {"@East Spirit City/Green House/Pots"},
    [800] = {"@East Spirit City/Crypt Pots/Pots"},
    [801] = {"@East Spirit City/Crypt Pots/Pots"},
    [802] = {"@East Spirit City/Crypt Pots/Pots"},
    [803] = {"@Early Ghost Castle/Three Gardens Pots/Pots"},
    [804] = {"@Early Ghost Castle/Three Gardens Pots/Pots"},
    [805] = {"@Early Ghost Castle/Ghost Stairwell Lower Pots/Pots"},
    [806] = {"@Early Ghost Castle/Ghost Stairwell Lower Pots/Pots"},
    [807] = {"@Early Ghost Castle/Ghost Stairwell Mid Pots/Pots"},
    [808] = {"@Early Ghost Castle/Ghost Stairwell Mid Pots/Pots"},
    [809] = {"@Early Ghost Castle/Ghost Stairwell Mid Pots/Pots"},
    [810] = {"@Early Ghost Castle/Ghost Stairwell Mid Pots/Pots"},
    [811] = {"@Early Ghost Castle/Ghost Stairwell Mid Pots/Pots"},
    [812] = {"@Rose Garden/Large Garden Pots/High Pots"},
    [813] = {"@Rose Garden/Large Garden Pots/High Pots"},
    [814] = {"@Rose Garden/Large Garden Pots/High Pots"},
    [815] = {"@Rose Garden/Large Garden Pots/High Pots"},
    [816] = {"@Rose Garden/Large Garden Pots/Pots"},
    [817] = {"@Rose Garden/Large Garden Pots/Pots"},
    [818] = {"@Rose Garden/Ladder Room Pots/Pots"},
    [819] = {"@Rose Garden/Ladder Room Pots/Pots"},
    [820] = {"@Rose Garden/Ladder Room Pots/Pots"},
    [821] = {"@Rose Garden/Drop Down Lower Pots/Pots"},
    [822] = {"@Rose Garden/Drop Down Lower Pots/Pots"},
    [823] = {"@Rose Garden/Drop Down Lower Pots/Pots"},
    [824] = {"@Thimble Ghost Castle/Large Hallway Pots/Pots"},
    [825] = {"@Thimble Ghost Castle/Large Hallway Pots/Pots"},
    [826] = {"@Tall Tower/Tall Tower Pots/Pots"},
    [827] = {"@Tall Tower/Tall Tower Pots/Pots"},
    [828] = {"@Tall Tower/Tall Tower Pots/Pots"},
    [829] = {"@Tall Tower/Tall Tower Pots/Pots"},
    [830] = {"@Top of Ghost Castle/Crumbling Room Pots/Pots"},
    [831] = {"@Top of Ghost Castle/Crumbling Room Pots/Pots"},
    [832] = {"@Top of Ghost Castle/Willow the Whiff Room Pots/Pots"},
    [833] = {"@Top of Ghost Castle/Willow the Whiff Room Pots/Pots"},
    [834] = {"@Top of Ghost Castle/Willow the Whiff Room Pots/Pots"},
    [835] = {"@Top of Ghost Castle/Willow the Whiff Room Pots/Pots"},
    [836] = {"@Top of Ghost Castle/Willow the Whiff Room Pots/Pots"},
    [837] = {"@Top of Ghost Castle/Willow the Whiff Room Pots/Pots"},
    [838] = {"@East Jigoku/The Mound Pots/Pots"},
    [839] = {"@East Jigoku/The Mound Pots/Pots"},
    [840] = {"@East Jigoku/The Mound Pots/Pots"},
    [841] = {"@East Jigoku/The Mound Pots/Pots"},
    [842] = {"@East Jigoku/The Mound Pots/Pots"},
    [843] = {"@East Jigoku/Long Hallway Pots/Pots"},
    [844] = {"@East Jigoku/Long Hallway Pots/Pots"},
    [845] = {"@East Jigoku/Long Hallway Pots/Pots"},
    [846] = {"@East Jigoku/Long Hallway Pots/Pots"},
    [847] = {"@East Jigoku/Long Hallway Pots/Pots"},
    [848] = {"@East Jigoku/Long Hallway Pots/Pots"},
    [849] = {"@East Jigoku/Long Hallway Pots/Pots"},
    [850] = {"@Lower Jigoku/First Drop Lower Pots/Pots"},
    [851] = {"@Lower Jigoku/First Drop Lower Pots/Pots"},
    [852] = {"@Lower Jigoku/First Drop Lower Pots/Pots"},
    [853] = {"@Early Jigoku/First Drop Higher Pots/Pots"},
    [854] = {"@Early Jigoku/First Drop Higher Pots/Pots"},
    [855] = {"@Early Jigoku/First Drop Higher Pots/Pots"},
    [856] = {"@Lower Jigoku/Boxy Drop Pots/Pots"},
    [857] = {"@Lower Jigoku/Boxy Drop Pots/Pots"},
    [858] = {"@Club Demon/Green Stairwell Pots/Pots"},
    [859] = {"@Club Demon/Green Stairwell Pots/Pots"},
    [860] = {"@Slime Citadel/Double Bananas Pots/Pots"},
    [861] = {"@Slime Citadel/Double Bananas Pots/Pots"},
    [862] = {"@Slime Citadel/Pillars Pots/Pots"},
    [863] = {"@Slime Citadel/Pillars Pots/Pots"},
    [864] = {"@Slime Citadel/Pillars Pots/Pots"},
    [865] = {"@Slime Citadel/Reward Pots/Pots"},
    [866] = {"@Slime Citadel/Reward Pots/Pots"},
    [867] = {"@Slime Citadel/Reward Pots/Pots"},
    [868] = {"@Slime Citadel/Reward Pots/Pots"},
    [869] = {"@Slime Citadel/Reward Pots/Pots"},
    [870] = {"@Slime Citadel/Reward Pots/Pots"},
    [871] = {"@Slime Citadel/Reward Pots/Pots"},
    [872] = {"@Slime Citadel/Reward Pots/Pots"},
    [873] = {"@Angelic Hallway/Cloudia Entrance Pots/Pots"},
    [874] = {"@Angelic Hallway/Cloudia Entrance Pots/Pots"},
    [875] = {"@Angelic Hallway/Cloudia Entrance Pots/Pots"},
    [876] = {"@Angelic Hallway/Cloudia Entrance Pots/Pots"},
    [877] = {"@Angelic Hallway/Cloudia Entrance Pots/Pots"},
    [878] = {"@Angelic Hallway/Cloudia Entrance Pots/Pots"},
    [879] = {"@Angelic Hallway/Cloudia Entrance Pots/Pots"},
    [880] = {"@Angelica Angelic/Cloud Ramp Pots/Pots"},
    [881] = {"@Angelica Angelic/Cloud Ramp Pots/Pots"},
    [882] = {"@Angelica Angelic/Cloud Ramp Pots/Pots"},
    [883] = {"@Angelica Angelic/Cloud Ramp Pots/Pots"},
    [884] = {"@Angelica Angelic/Cloud Ramp Pots/Pots"},
    [885] = {"@Angelica Angelic/Flower Garden Pots/Pots"},
    --[886] = {"@Angelica Angelic/Flower Garden Pots/Pots"},
    [887] = {"@Angelica Angelic/Flower Garden Pots/Pots"},
    [888] = {"@Angelica Angelic/Flower Garden Pots/Pots"},
    [889] = {"@Angelica Angelic/Flower Garden Pots/Pots"},
    [890] = {"@Angelica Angelic/Flower Garden Pots/Pots"},
    [891] = {"@Angelica Angelic/Flower Garden Pots/Pots"},
    [892] = {"@Umi Umi/Surfacing Pots/Pots"},
    [893] = {"@Umi Umi/Surfacing Pots/Pots"},
    [894] = {"@Umi Umi/Diving Deeper Pots/Pots"},
    [895] = {"@Umi Umi/Diving Deeper Pots/Pots"},
    [896] = {"@Umi Umi/Diving Deeper Pots/Pots"},
    [897] = {"@Umi Umi/Diving Deeper Pots/Pots"},
    [898] = {"@Umi Umi/Mermaid's Chest/Diving Pots"},
    [899] = {"@Umi Umi/Mermaid's Chest/Diving Pots"},
    [900] = {"@Goblin Tower/Goblin Camp Lower Pots/Pots"},
    [901] = {"@Goblin Tower/Goblin Camp Lower Pots/Pots"},
    [902] = {"@Goblin Tower/Goblin Camp Lower Pots/Pots"},
    [903] = {"@Club Demon/Green Stairwell Pots/Pots"},
    
}
