-- use this file to map the AP item ids to your items
-- first value is the code of the target item and the second is the item type (currently only "toggle", "progressive" and "consumable" but feel free to expand for your needs!)
-- here are the SM items as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/item_mapping.lua
local base_id = 0

ITEM_MAPPING = {
    [151] = { "FBubble", "toggle" },
    [204] = { "BBell", "toggle" },
    [205] = { "GLug", "toggle" },
    [206] = { "SStone", "consumable" },
    [207] = { "DMilk", "toggle" },
    [208] = { "BMilk", "toggle" },
    [209] = { "CAKey", "toggle" },
    [210] = { "MPass", "toggle" },
    [211] = { "BClothes", "toggle" },
    [212] = { "HDaikon", "toggle" },
    [213] = { "HDango", "toggle" },
    [214] = { "SFrag", "consumable" },
    [215] = { "LHalo", "toggle" },
    [216] = { "DLetter", "toggle" },
    [217] = { "ALetter", "toggle" },
    [218] = { "SSlime", "toggle" },
    [219] = { "RWine", "toggle" },
    [220] = { "BJelly", "toggle" },
    [221] = { "MContract", "toggle" },
    [222] = { "FDeed", "toggle" },
    [223] = { "MimicKey", "toggle" },
    [224] = { "FKey", "toggle" },
    [225] = { "GAKey", "toggle" },
    [201] = { "GHead", "toggle" },
    [202] = { "GCard", "toggle" },
    [203] = { "VIPKey", "toggle" },
    -- [1] = { "Goblin Bomb", "toggle" },
     --[152] = { "Frilly Panties", "toggle" },
    -- [153] = { "Disarming Bell", "toggle" },
    [2] = { "GForm", "toggle" },
    [3] = { "SForm", "toggle" },
    -- [4] = { "Harpy Feather", "toggle" },
    -- [156] = { "Magical Mushroom", "toggle" },
    --[158] = { "Slime Sentry", "toggle" },
    -- [155] = { "Ring Of The Moon", "toggle" },
    -- [157] = { "Ring Of The Sun", "toggle" },
    -- [159] = { "Haunted Scythe", "toggle" },
    --[154] = { "Demonic Cuff", "toggle" },
    [160] = { "FCat", "toggle" },
    -- [161] = { "Heart Necklace", "toggle" },
   -- [162] = { "Star Bracelet", "toggle" },
   -- [5] = { "Magnetic Hairpin", "toggle" },
   -- [164] = { "Yellow Frog Talisman", "toggle" },
   -- [165] = { "Blue Frog Talisman", "toggle" },
   -- [6] = { "Sacrificial Dagger", "toggle" },
   -- [166] = { "Mind Mushroom", "toggle" },
   -- [7] = { "Flutterknife Garter", "toggle" },
   -- [163] = { "Cursed Talisman", "toggle" },
    [8] = { "HP", "consumable" }, 
    [9] = { "MP", "consumable" }, 
    --[10] = { "Wand Upgrade", "toggle" },
    [11] = { "Peach", "consumable" },
    [12] = { "BBubble", "toggle" },
    [13] = { "GCrystal", "toggle" },
    [167] = { "PPCrystal", "toggle" },
    [14] = { "DWings", "toggle" },
    [15] = { "AFeather", "toggle" },
    [16] = { "MScale", "toggle" },
    --[17] = { "Lucky Coin", "toggle" },
    --[18] = { "Loose Change", "toggle" },
    [19] = { "WCB", "toggle" },
    [20] = { "CCB", "toggle" },
    [21] = { "BlackCos", "toggle" },
    [22] = { "RedCos", "toggle" },
    [170] = { "NunCos", "toggle" },
    [171] = { "PriestCos", "toggle" },
    [172] = { "MikoCos", "toggle" },
    [173] = { "FarmCos", "toggle" },
    [168] = { "CatCos", "toggle" },
    [169] = { "GobCos", "toggle" },
    [176] = { "MaidCos", "toggle" },
    [177] = { "PigCos", "toggle" },
    [227] = { "BunCos", "toggle" },
    [23] = { "RatCos", "toggle" },
    [174] = { "NurseCos", "toggle" },
    [25] = { "FishCos", "toggle" },
    [178] = { "DomCos", "toggle" },
    [175] = { "MailCos", "toggle" },
    [26] = { "FairyCos", "toggle" },
    [179] = { "AlchCos", "toggle" },
    [27] = { "RHKey", "toggle" },
    [28] = { "GCKey", "toggle" },
    [29] = { "TBKey", "toggle" },
    [30] = { "SCDKey", "toggle" },
    [31] = { "SCKey", "toggle" },
    [32] = { "FBKey", "toggle" },
    [33] = { "GQKey", "toggle" },
    [34] = { "RGKey", "toggle" },
    [35] = { "CTKey", "toggle" },
    [36] = { "DBKey", "toggle" },
    [37] = { "SSBKey", "toggle" },
    [38] = { "CSKey", "toggle" },
    [228] = { "AAKey", "toggle" },
    [40] = { "SGKey", "toggle" },
    [41] = { "CDKey", "toggle" },
    [42] = { "SBKey", "toggle" },
    [43] = { "FFDKey", "toggle" },
    [45] = { "ChaosK", "consumable" },
    --[46] = { "HP Heal", "toggle" },
    --[47] = { "MP Heal", "toggle" },
    --[48] = { "Peach Recharge", "toggle" },
    --[302] = { "Sex Thoughts", "toggle" },
    --[49] = { "Armor Barrier", "consumable" },
    --[226] = { "Sex Experience", "consumable" },
    --[301] = { "Nothing", "toggle" },
    [50] = { "Peachy Peach Upgrade", "toggle" },
    [107] = { "AGacha", "consumable" },
    [108] = { "BGacha", "consumable" },
    [109] = { "ADGacha", "consumable" },
    [110] = { "MGacha", "consumable" },
    [111] = { "PGacha", "toggle" },

    --Warps
    [251] = {"Sensei Warp", "toggle"},
    [252] = {"Witchy Warp", "toggle"},
    [253] = {"Goblin Warp", "toggle"},
    [254] = {"Spirit Warp", "toggle"},
    [255] = {"Shady Warp", "toggle"},
    [256] = {"Ghost Entrace Warp", "toggle"},
    [257] = {"Ghost Castle Warp", "toggle"},
    [258] = {"Jigoku Warp", "toggle"},
    [259] = {"Club Demon Warp", "toggle"},
    [260] = {"Tengoku Warp", "toggle"},
    [261] = {"Angelic Hallway Warp", "toggle"},
    [262] = {"Fungal Forest Warp", "toggle"},
    [263] = {"Slime_Citadel Warp", "toggle"},
    [264] = {"Slimy_Depths Warp", "toggle"},
    [265] = {"Umi Umi Warp", "toggle"},
    [266] = {"Chaos Castle Warp", "toggle"},
}
    

--[[     #Gacha 
    #"SP Figure 1":101,
    #"AG Figure 1":102,
    #"AG Figure 2":103,
    #"AG Figure 3":104,
    #"AG Figure 4":105,
    #"AG Figure 5":106,
    #"AG Figure 6":107,
    #"AG Figure 7":108,
    #"AG Figure 8":109,
    #"AG Figure 9":110,
    #"AG Figure 10":111,
    #"BG Figure 1":112,
    #"BG Figure 2":113,
    #"BG Figure 3":114,
    #"BG Figure 4":115,
    #"BG Figure 5":116,
    #"BG Figure 6":117,
    #"BG Figure 7":118,
    #"BG Figure 8":119,
    #"BG Figure 9":120,
    #"BG Figure 10":121,
    #"AD Figure 1":122,
    #"AD Figure 2":123,
    #"AD Figure 3":124,
    #"AD Figure 4":125,
    #"AD Figure 5":126,
    #"AD Figure 6":127,
    #"AD Figure 7":128,
    #"AD Figure 8":129,
    #"AD Figure 9":130,
    #"AD Figure 10":131,
    #"MG Figure 1":132,
    #"MG Figure 2":133,
    #"MG Figure 3":134,
    #"MG Figure 4":135,
    #"MG Figure 5":136,
    #"MG Figure 6":137,
    #"MG Figure 7":138,
    #"MG Figure 8":139,
    #"MG Figure 9":140,
    #"MG Figure 10":141,
#} ]]
